# Generated by Django 5.2.7 on 2025-10-17 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='compressed_content',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
    ]
